param_dic:
  # dates
  year: 2014
  month: 5
  day: 29

  # data_paths
  data_file_path: '{home}/data/{year:04}/{month:02}/{day:02}/'
  run_name: 'test'

  # Switches
  assim_flag: 0
  perturbation_flag: 0
  div_flag: 0
  assim_of_flag: 0
  assim_sat2sat_flag: 0
  assim_sat2wind_flag: 0
  assim_wrf_flag: 0

  # advection_params
  start_time: 0
  end_time: 0
  C_max: 0.7
  max_horizon: '1hour'
  client_address: '127.0.0.1:8786'

  # assimilation_params
  # assim_sat2sat
  sig_sat2sat: 0.05
  loc_sat2sat: 1*4
  infl_sat2sat: 1.5
  assim_gs_sat2sat: 20
  # assim_sat2wind
  sig_sat2wind: 1
  loc_sat2wind: 30*4
  infl_sat2wind: 4
  assim_gs_sat2wind: 20
  # assim_wrf
  sig_wrf: 0.5
  infl_wrf: 1
  loc_wrf: 1*4
  assim_gs_wrf: 5
  # assim_OF
  sig_of: 1
  loc_of: 20  # in km not grid spaces
  infl_of: 4

  # ensemble_params
  ens_num: 20
  winds_sigma: (1, 1)
  ci_sigma: 0.4

  # perturbation_params
  Lx: 5
  Ly: 5
  tol: 0.005
  pert_sigma: 0.15/3
  pert_mean: 0
  edge_weight: 1
