date:
  year: null
  month: null
  day: null

io:
  data_file_path: '{home}/data/{year:04}/{month:02}/{day:02}/data.nc'
  run_name: 'wrf_mean'

flags:
  assim: 0
  perturbation: 0
  div: 0
  assim_opt_flow: 0
  assim_sat2sat: 0
  assim_sat2wind: 0
  assim_wrf: 0
  wrf_mean: 1
  opt_flow: 0
  perturb_winds: 0
  radiosonde: 0
  name: 'flag'

advect_params:
  start_time: 0
  end_time: 0
  C_max: 0.7
  max_horizon: '1hour'

ens_params:
  ens_num: 1
  winds_sigma: !!python/tuple [null, null]
  ci_sigma: null

pert_params:
  Lx: null
  Ly: null
  tol: null
  pert_sigma: null
  pert_mean: null
  edge_weight: null

  Lx_wind: null
  Ly_wind: null
  tol_wind: null
  pert_sigma_wind: null
  pert_mean_wind: null

# assimilation_params
sat2sat:
  sig: null
  loc: null
  infl: null
  grid_size: null
  name: 'sat2sat'
sat2wind:
  sig: null
  loc: null
  infl: null
  grid_size: null
  name: 'sat2wind'
wrf:
  sig: null
  infl: null
  loc: null
  grid_size: null
  name: 'wrf'
opt_flow:
  sig: null
  loc: null  # in km not grid spaces
  infl: null
  name: 'opt_flow'
