date:
  year: 2014
  month: 5
  day: 29

io:
  data_file_path: '{home}/data/{year:04}/{month:02}/{day:02}/data.nc'
  run_name: 'test'

flags:
  assim: 0
  perturbation: 0
  div: 0
  assim_of: 0
  assim_sat2sat: 0
  assim_sat2wind: 0
  assim_wrf: 0
  name: 'flag'

advect_params:
  start_time: 0
  end_time: 0
  C_max: 0.7
  max_horizon: '1hour'
  client_address: '127.0.0.1:8786'

ens_params:
  ens_num: 20
  winds_sigma: (1, 1)
  ci_sigma: 0.4

pert_params:
  Lx: 5
  Ly: 5
  tol: 0.005
  pert_sigma: 0.15/3
  pert_mean: 0
  edge_weight: 1

# assimilation_params
sat2sat:
  sig: 0.05
  loc: 1*4
  infl: 1.5
  grid_size: 20
  name: 'sat2sat'
sat2wind:
  sig: 1
  loc: 30*4
  infl: 4
  grid_size: 20
  name: 'sat2wind'
wrf:
  sig: 0.5
  infl: 1
  loc: 1*4
  grid_size: 5
  name: 'wrf'
opt_flow:
  sig: 1
  loc: 20  # in km not grid spaces
  infl: 4
  name: 'of'
